fileList = struct('files', ['D:\MyJavaProjects\Spharm\data\Easp_ME_6_4_OL_2O.m'; ...
'D:\MyJavaProjects\Spharm\data\Easp_ME_7_1_OL_2O.m'; ...
'D:\MyJavaProjects\Spharm\data\Easp_ME_7_3_OL_2O.m'; ...
], 'template', ['D:\MyJavaProjects\Spharm\data\template_Easp_ME_6_4_OL_CS_2O_15_0_des.mat'; ...
]);